#
# Pently audio engine
# Sample drums
#
# Copyright 2001-2018 Damian Yerrick
# 
# This software is provided 'as-is', without any express or implied
# warranty.  In no event will the authors be held liable for any damages
# arising from the use of this software.
# 
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
# 
# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source distribution.
#

sfx kick on noise
  volume 12 10 8 6 5 4 3 2 1 1
  pitch 10 0

sfx snare on noise
  volume 12 10 8 6 5 4 3 2 1 1
  pitch 4 10

sfx hihat on noise
  volume 4 2 2 1
  pitch 12
  timbre | 0 1

sfx openhat on noise
  volume 6 5 4 4 3:3 2:3 1:5
  pitch 12
  timbre | 0 1

sfx snarehat on noise
  volume 12 10 8 6 3:3 2:3 1:5
  pitch 4 10 10 12
  timbre 0 0 | 0 1

sfx trikick on triangle
  volume 15 15 15 2 2
  pitch e' c' a f# e

sfx trisnare on triangle
  volume 15 15 2 2
  pitch bb' ab' g' f#'

drum kick kick
drum snare snare
drum clhat hihat
drum ohat openhat
drum tkick kick trikick
drum tsnare snare trisnare
drum tsohat snarehat trisnare

